import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
import Drawer from "~/components/Drawer";

// styles
import "bootstrap/dist/css/bootstrap.css";

// Constants
const navItems = [{ path: "/", text: "Home" }];

function MyApp({ Component, pageProps }) {
  // const router = useRouter();

  return (
    <>
      <Head>
        <title>React Hooks Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar brand="React Hooks Training" navItems={navItems} />
      <div className="container">
        <div className="row">
          <div className="col-2">
            <Drawer />
          </div>
          <div className="col-10 border-start border-light ps-4">
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </>
  );
}

export default MyApp;
