import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../components/Navbar";
import "bootstrap/dist/css/bootstrap.css";
import Sidebar from "~/components/Sidebar";
import List from "~/components/List";

// Constants

const useRefApps = [
  { path: "/use-ref/apps/focus-app", text: "Focus" },
  { path: "/use-ref/apps/copy-app", text: "Copy" },
  { path: "/use-ref/apps/media-player-app", text: "Media Player" },
  { path: "/use-ref/apps/scroll-animation-app", text: "Scroll Animation" },
  { path: "/use-ref/apps/render-app", text: "Render" },
  { path: "/use-ref/apps/loading-app", text: "Loading" },
];

const customHooksApps = [
  { path: "/custom-hooks/apps/mouse-position-app", text: "useMousePosition" },
];

const navItems = [{ path: "/", text: "Home" }];

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>React Hooks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar brand="React Hooks" navItems={navItems} />
      <div className="container">
        <div className="row">
          <div className="col-2">
            <h5>useState</h5>
            <h5>useRef</h5>
            <List title="useRef" listItems={useRefApps} />
            <h5>useReducer</h5>
            <h5>useImperativeHandle</h5>
            <h5>useRef</h5>
            <h5>useCallback</h5>
            <h5>useMemo</h5>
            <h5>Custom Hooks</h5>
            <List title="useRef" listItems={customHooksApps} />
          </div>
          <div className="col-10 border-start border-light ps-4">
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </>
  );
}

export default MyApp;
